---
- name: VIRTUALBOX | add vb secure key
  become: true
  apt_key:
    url: "{{ virtualbox_apt_key_url }}"
    state: present
  when: ( ansible_distribution == 'Debian' and ansible_distribution_version >= '8' ) or
        ( ansible_distribution == 'Ubuntu' and ansible_distribution_version >= '16.04' )

- name: VIRTUALBOX | add vb secure key (old)
  become: true
  apt_key:
    url: "{{ virtualbox_apt_key_url_old }}"
    state: present
  when: ( ansible_distribution == 'Debian' and ansible_distribution_version < '8' ) or
        ( ansible_distribution == 'Ubuntu' and ansible_distribution_version < '16.04' )

- name: VIRTUALBOX | add paket sources
  become: true
  apt_repository:
    repo: "deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
    state: present

- name: VIRTUALBOX | install virtualbox
  become: true
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "linux-headers-{{ ansible_kernel }}"
    - dkms
    - build-essential
    - "virtualbox-{{ virtualbox_version }}"

- name: VIRTUALBOX | add users to vb-group
  become: true
  user:
    name: "{{ item }}"
    groups: vboxusers
    append: yes
  with_items: "{{ virtualbox_users }}"
